name: Pull Request Merge
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PR Opened
        run: echo PR opened!

      - name: PR Merged / Code Pushed
        if: ${{ github.event_name == 'push' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Analyze Code
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: '{ "message": "Analyzing code!", "commit_hash": "${{ github.event.pull_request.head.sha }}" }'
        
      - name: PR Closed
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false }}
        run: echo PR closed!
